### ISSUE TITLE
MAINT: update pyvo and astroquery versions

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-images#5]
I coundn't log into gitlab, thus opening this issue here. Our users reported the old version of pyvo in the image, would it be possible to upgrade it (so we have the fixes to SIA2 available on the platform).

And while we're at it, it would be great to have the latest released version of astroquery, too (~~0.4.7~~ it should be the latest dev version from pypi (at least 0.4.8.dev9306/), picked up with `pip install -U --pre astroquery` as we need the fix for https://github.com/fornax-navo/fornax-demo-notebooks/issues/265)

cc @zoghbi-a

**Comment by zoghbi-a** [comment]
Since our images don't have version tags, these got updated when the image was re-built last week.
The update fixed this issue, but this behavior is undesired generally. #8 will track adding tags to ensure reproducibility of the image builds.

This issue can be closed.

**Comment by bsipocz** [comment]
Thanks for the updates!
